# Generated by Django 6.0.4 on 2026-04-26 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF or DOCX only", upload_to="resumes/%Y/%m/%d/"
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to="candidates.candidateprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
            },
        ),
    ]
